### ISSUE TITLE
不错的项目，支持一下。有个问题，怎么开发呢？动态更新呢

### ISSUE THREAD

**Issue by zhaopengme** [lizc2003/gossr#2]
不错的项目，支持一下。有个问题，怎么开发呢？
无论前端还是后端，都需要动态开发把。谢谢

**Comment by lizc2003** [comment]
除非有特定的需求，目前的后端已经满足需求，不需要再开发。
开发的工作主要是前端，就是开发jsproj目录下的vue代码。

**Comment by zhaopengme** [comment]
谢谢  我意思是前端开发的时候 有个类似  npm run dev 的命令 前端可以实时编译开发

**Comment by lizc2003** [comment]
新增了一个npm run watch的命令， 可以满足这个需求。
